export enum AnimalEmoji {
    Bear = "emojione:bear-face",
    BlackCat = "emojione:cat-face",
    Cat = "emojione:cat-face-with-wry-smile",
    Dog = "emojione:dog-face",
    Dragon = "emojione:dragon-face",
    Fox = "emojione:fox-face",
    Frog = "emojione:frog-face",
    Hamster = "emojione:hamster-face",
    Horse = "emojione:horse-face",
    Lion = "emojione:lion-face",
    Monkey = "emojione:monkey-face",
    Mouse = "emojione:mouse-face",
    Panda = "emojione:panda-face",
    Pig = "emojione:pig-face",
    Rabbit = "emojione:rabbit-face",
    Tiger = "emojione:tiger-face",
    Unicorn = "emojione:unicorn-face",
    Wolf = "emojione:wolf-face",
}
